name: publish

on: 
  workflow_dispatch
    
jobs:

  publish:
    runs-on: ubuntu-latest
    
    env:        
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   
      
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Build
        run: ./build.sh
        
      - name: Publish          
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
          BRANCH_NAME: 'main'
